### ISSUE TITLE
"Cannot find module ./build/Release/binding.node" error while using node-python

### ISSUE THREAD

**Issue by pluto5004** [JeanSebTr/node-python#4] opened 2013-10-09 04:56 UTC
![image](https://f.cloud.github.com/assets/5643976/1295003/d515a5a4-309c-11e3-96e7-545b26f499ce.png)

Node-python is able to install properly using npm install. But the above error occured when I tried to use it. 
I am using vagrant with precise32 box.
Node version - v 0.10.19 (also tried in v 0.6.x)
Python version - 2.7.3.

It would be very helpful, if anybody can resolve the issue. Please comment if any further information required.

**Comment by JeanSebTr** [comment] 2013-10-09 18:53
I couldn't reproduce your issue. Tried with precise32 box with both 0.6.x and 0.10.20...
For 0.6.x you need to manually compile with node-gyp because the build system of nodejs has changed since 0.6 but all should works.

Anyway I've published node-python v0.0.4 which use bindings to load the native extension. Lets hope that works.
If you still have the issue, it should be because the module it not compiled at all.

**Comment by JeanSebTr** [comment] 2014-02-05 00:00
I've not ear back from you and v0.0.4 should fix the issue anyway, closing the issue.

**Closed as completed by JeanSebTr** 2014-02-05 00:00 UTC
